/**
 * @namespace CityArtWalks.Components.Icons.AddUserIcon
 * @version 1.0.0
 * @author Generated by icon component generator
 * @memberof CityArtWalks.Components.Icons
 * @description Add user icon component using Iconify.
 */

import { Iconify } from 'src/components/iconify';

/**
 * @memberof CityArtWalks.Components.Icons.AddUserIcon
 * @function AddUserIcon
 * @description Renders an add user icon using the Iconify component.
 *
 * @component
 * @param {Object} props - The component props.
 * @param {number} [props.size=24] - The size of the icon in pixels.
 * @param {Object} [props.sx={}] - Additional Material-UI sx styling props.
 * @returns {JSX.Element} The rendered AddUserIcon component.
 *
 * @example
 * <AddUserIcon size={16} />
 * <AddUserIcon size={24} sx={{ color: 'primary.main' }} />
 */
export function AddUserIcon({ size = 24, sx = {}, ...props }) {
  return (
    <Iconify icon="solar:user-plus-bold-duotone" width={size} height={size} sx={sx} {...props} />
  );
}
