/**
 * @namespace CityArtWalks.Components.Icons.ArrowRightIcon
 * @version 1.0.0
 * @author Generated by icon component generator
 * @memberof CityArtWalks.Components.Icons
 * @description Arrow Right Icon icon component using Iconify.
 */

import { Iconify } from 'src/components/iconify';

/**
 * @memberof CityArtWalks.Components.Icons.ArrowRightIcon
 * @function ArrowRightIcon
 * @description Renders a arrow right icon icon using the Iconify component.
 *
 * @component
 * @param {Object} props - The component props.
 * @param {number} [props.size=24] - The size of the icon in pixels.
 * @param {Object} [props.sx={}] - Additional Material-UI sx styling props.
 * @returns {JSX.Element} The rendered ArrowRightIcon component.
 *
 * @example
 * <ArrowRightIcon size={16} />
 * <ArrowRightIcon size={24} sx={{ color: 'primary.main' }} />
 */
export function ArrowRightIcon({ size = 24, sx = {}, ...props }) {
  return <Iconify icon="solar:arrow-right-bold" width={size} height={size} sx={sx} {...props} />;
}
