/**
 * @namespace CityArtWalks.Components.Icons.BookmarkIcon
 * @version 1.0.0
 * @author Generated by icon component generator
 * @memberof CityArtWalks.Components.Icons
 * @description Bookmark Icon icon component using Iconify.
 */

import { Iconify } from 'src/components/iconify';

/**
 * @memberof CityArtWalks.Components.Icons.BookmarkIcon
 * @function BookmarkIcon
 * @description Renders a bookmark icon icon using the Iconify component.
 *
 * @component
 * @param {Object} props - The component props.
 * @param {number} [props.size=24] - The size of the icon in pixels.
 * @param {Object} [props.sx={}] - Additional Material-UI sx styling props.
 * @returns {JSX.Element} The rendered BookmarkIcon component.
 *
 * @example
 * <BookmarkIcon size={16} />
 * <BookmarkIcon size={24} sx={{ color: 'primary.main' }} />
 */
export function BookmarkIcon({ size = 24, sx = {}, ...props }) {
  return (
    <Iconify icon="solar:bookmark-bold-duotone" width={size} height={size} sx={sx} {...props} />
  );
}
