/**
 * @namespace CityArtWalks.Components.Icons.ChevronDownIcon
 * @version 1.0.0
 * @author Generated by icon component generator
 * @memberof CityArtWalks.Components.Icons
 * @description Chevron Down icon component using solar:arrow-down-bold for dropdown controls.
 */

import { Iconify } from 'src/components/iconify';

/**
 * @memberof CityArtWalks.Components.Icons.ChevronDownIcon
 * @function ChevronDownIcon
 * @description Renders a chevron down icon using the solar:arrow-down-bold icon.
 * Commonly used for dropdown indicators, expand controls, and collapsible sections.
 *
 * @component
 * @param {Object} props - The component props.
 * @param {number} [props.size=24] - The size of the icon in pixels.
 * @param {Object} [props.sx={}] - Additional Material-UI sx styling props.
 * @returns {JSX.Element} The rendered ChevronDownIcon component.
 *
 * @example
 * <ChevronDownIcon size={16} />
 * <ChevronDownIcon size={24} sx={{ color: 'primary.main' }} />
 */
export function ChevronDownIcon({ size = 24, sx = {}, ...props }) {
  return (
    <Iconify
      icon="solar:arrow-down-bold"
      width={size}
      sx={{ width: size, height: size, ...sx }}
      {...props}
    />
  );
}
