/**
 * @namespace CityArtWalks.Components.Icons.ForwardIcon
 * @version 1.0.0
 * @author Generated by icon component generator
 * @memberof CityArtWalks.Components.Icons
 * @description Forward Icon icon component using Iconify.
 */

import { Iconify } from 'src/components/iconify';

/**
 * @memberof CityArtWalks.Components.Icons.ForwardIcon
 * @function ForwardIcon
 * @description Renders a forward icon icon using the Iconify component.
 *
 * @component
 * @param {Object} props - The component props.
 * @param {number} [props.size=24] - The size of the icon in pixels.
 * @param {Object} [props.sx={}] - Additional Material-UI sx styling props.
 * @returns {JSX.Element} The rendered ForwardIcon component.
 *
 * @example
 * <ForwardIcon size={16} />
 * <ForwardIcon size={24} sx={{ color: 'primary.main' }} />
 */
export function ForwardIcon({ size = 24, sx = {}, ...props }) {
  return <Iconify icon="solar:arrow-right-bold" width={size} height={size} sx={sx} {...props} />;
}
