/**
 * @namespace CityArtWalks.Components.Icons.InboxIcon
 * @version 1.0.0
 * @author Generated by icon component generator
 * @memberof CityArtWalks.Components.Icons
 * @description Inbox Icon icon component using Iconify.
 */

import { Iconify } from 'src/components/iconify';

/**
 * @memberof CityArtWalks.Components.Icons.InboxIcon
 * @function InboxIcon
 * @description Renders a inbox icon icon using the Iconify component.
 *
 * @component
 * @param {Object} props - The component props.
 * @param {number} [props.size=24] - The size of the icon in pixels.
 * @param {Object} [props.sx={}] - Additional Material-UI sx styling props.
 * @returns {JSX.Element} The rendered InboxIcon component.
 *
 * @example
 * <InboxIcon size={16} />
 * <InboxIcon size={24} sx={{ color: 'primary.main' }} />
 */
export function InboxIcon({ size = 24, sx = {}, ...props }) {
  return <Iconify icon="solar:inbox-bold-duotone" width={size} height={size} sx={sx} {...props} />;
}
