/**
 * @namespace CityArtWalks.Components.Icons.MoneyIcon
 * @version 1.0.0
 * @author Generated by icon component generator
 * @memberof CityArtWalks.Components.Icons
 * @description Money Icon icon component using Iconify.
 */

import { Iconify } from 'src/components/iconify';

/**
 * @memberof CityArtWalks.Components.Icons.MoneyIcon
 * @function MoneyIcon
 * @description Renders a money icon icon using the Iconify component.
 *
 * @component
 * @param {Object} props - The component props.
 * @param {number} [props.size=24] - The size of the icon in pixels.
 * @param {Object} [props.sx={}] - Additional Material-UI sx styling props.
 * @returns {JSX.Element} The rendered MoneyIcon component.
 *
 * @example
 * <MoneyIcon size={16} />
 * <MoneyIcon size={24} sx={{ color: 'primary.main' }} />
 */
export function MoneyIcon({ size = 24, sx = {}, ...props }) {
  return <Iconify icon="solar:dollar-bold-duotone" width={size} height={size} sx={sx} {...props} />;
}
