/**
 * @namespace CityArtWalks.Components.Icons.PrintIcon
 * @version 1.0.0
 * @author Generated by icon component generator
 * @memberof CityArtWalks.Components.Icons
 * @description Print Icon icon component using Iconify.
 */

import { Iconify } from 'src/components/iconify';

/**
 * @memberof CityArtWalks.Components.Icons.PrintIcon
 * @function PrintIcon
 * @description Renders a print icon icon using the Iconify component.
 *
 * @component
 * @param {Object} props - The component props.
 * @param {number} [props.size=24] - The size of the icon in pixels.
 * @param {Object} [props.sx={}] - Additional Material-UI sx styling props.
 * @returns {JSX.Element} The rendered PrintIcon component.
 *
 * @example
 * <PrintIcon size={16} />
 * <PrintIcon size={24} sx={{ color: 'primary.main' }} />
 */
export function PrintIcon({ size = 24, sx = {}, ...props }) {
  return (
    <Iconify icon="solar:printer-minimalistic-bold" width={size} height={size} sx={sx} {...props} />
  );
}
