/**
 * @namespace CityArtWalks.Components.Icons.RestartIcon
 * @version 1.0.0
 * @author Generated by icon component generator
 * @memberof CityArtWalks.Components.Icons
 * @description Restart Icon icon component using Iconify.
 */

import { Iconify } from 'src/components/iconify';

/**
 * @memberof CityArtWalks.Components.Icons.RestartIcon
 * @function RestartIcon
 * @description Renders a restart icon icon using the Iconify component.
 *
 * @component
 * @param {Object} props - The component props.
 * @param {number} [props.size=24] - The size of the icon in pixels.
 * @param {Object} [props.sx={}] - Additional Material-UI sx styling props.
 * @returns {JSX.Element} The rendered RestartIcon component.
 *
 * @example
 * <RestartIcon size={16} />
 * <RestartIcon size={24} sx={{ color: 'primary.main' }} />
 */
export function RestartIcon({ size = 24, sx = {}, ...props }) {
  return <Iconify icon="solar:restart-bold" width={size} height={size} sx={sx} {...props} />;
}
