/**
 * Alias export for ShieldCheckIcon for dashboard navigation compatibility
 */
export const ShieldCheckIcon = ShieldCheckCircleIcon;
/**
 * @namespace CityArtWalks.Components.Icons.ShieldCheckCircleIcon
 * @version 1.0.0
 * @author Generated by icon component generator
 * @memberof CityArtWalks.Components.Icons
 * @description Shield Check Icon icon component using Iconify.
 */

import { Iconify } from 'src/components/iconify';

/**
 * @memberof CityArtWalks.Components.Icons.ShieldCheckCircleIcon
 * @function ShieldCheckCircleIcon
 * @description Renders a shield check icon icon using the Iconify component.
 *
 * @component
 * @param {Object} props - The component props.
 * @param {number} [props.size=24] - The size of the icon in pixels.
 * @param {Object} [props.sx={}] - Additional Material-UI sx styling props.
 * @returns {JSX.Element} The rendered ShieldCheckCircleIcon component.
 *
 * @example
 * <ShieldCheckCircleIcon size={16} />
 * <ShieldCheckCircleIcon size={24} sx={{ color: 'primary.main' }} />
 */
export function ShieldCheckCircleIcon({ size = 24, sx = {}, ...props }) {
  return (
    <Iconify icon="solar:shield-check-bold-duotone" width={size} height={size} sx={sx} {...props} />
  );
}
