/**
 * @namespace CityArtWalks.Components.Icons.SpeedIcon
 * @version 1.0.0
 * @author Generated by icon component generator
 * @memberof CityArtWalks.Components.Icons
 * @description Speed Icon icon component using Iconify.
 */

import { Iconify } from 'src/components/iconify';

/**
 * @memberof CityArtWalks.Components.Icons.SpeedIcon
 * @function SpeedIcon
 * @description Renders a speed icon icon using the Iconify component.
 *
 * @component
 * @param {Object} props - The component props.
 * @param {number} [props.size=24] - The size of the icon in pixels.
 * @param {Object} [props.sx={}] - Additional Material-UI sx styling props.
 * @returns {JSX.Element} The rendered SpeedIcon component.
 *
 * @example
 * <SpeedIcon size={16} />
 * <SpeedIcon size={24} sx={{ color: 'primary.main' }} />
 */
export function SpeedIcon({ size = 24, sx = {}, ...props }) {
  return (
    <Iconify icon="solar:speedometer-bold-duotone" width={size} height={size} sx={sx} {...props} />
  );
}
