/**
 * @namespace CityArtWalks.Components.Icons.VerifiedIcon
 * @version 1.0.0
 * @author Generated by icon component generator
 * @memberof CityArtWalks.Components.Icons
 * @description Verified Icon icon component using Iconify.
 */

import { Iconify } from 'src/components/iconify';

/**
 * @memberof CityArtWalks.Components.Icons.VerifiedIcon
 * @function VerifiedIcon
 * @description Renders a verified icon icon using the Iconify component.
 *
 * @component
 * @param {Object} props - The component props.
 * @param {number} [props.size=24] - The size of the icon in pixels.
 * @param {Object} [props.sx={}] - Additional Material-UI sx styling props.
 * @returns {JSX.Element} The rendered VerifiedIcon component.
 *
 * @example
 * <VerifiedIcon size={16} />
 * <VerifiedIcon size={24} sx={{ color: 'primary.main' }} />
 */
export function VerifiedIcon({ size = 24, sx = {}, ...props }) {
  return (
    <Iconify
      icon="solar:verified-check-bold-duotone"
      width={size}
      height={size}
      sx={sx}
      {...props}
    />
  );
}
