/**
 * @fileoverview Centralized API endpoint configuration for City Art Walks.
 * Maps frontend and backend API paths with role-based access control and command examples.
 *
 * @namespace CityArtWalks.Endpoints
 * @author Jaimie Garner
 * @version 2.0.0
 * @see {@link https://github.com/pacificnm/cityartwalks.com/wiki/Endpoints} - Complete documentation
 */
import { CONFIG } from "./global-config.js";

/**
 * @constant {string} SERVER
 * @description Server base URL resolved from configuration.
 * @memberof CityArtWalks.Endpoints
 */
export const SERVER = CONFIG.serverUrl || "http://localhost:5000";

/**
 * @typedef {Object} EndpointConfig
 * @description Standard configuration object for API endpoints.
 * @property {string} method - HTTP method (GET, POST, PUT, DELETE)
 * @property {string|Function} path - API path or function returning path
 * @property {string[]} roles - Required user roles ['public', 'USER', 'ADMIN']
 * @property {string} description - Human-readable endpoint description
 * @property {Function} command - Function returning example command/path
 * @memberof CityArtWalks.Endpoints
 */

/**
 * @constant {Object} endpoints
 * @description Main endpoints configuration object containing all API routes organized by resource.
 * Each endpoint includes method, path, roles, description, and command examples.
 * @memberof CityArtWalks.Endpoints
 * @see {@link https://github.com/pacificnm/cityartwalks.com/wiki/Endpoints} - Complete documentation
 */
export const endpoints = {
  analytics: {
    event: {
      method: "POST",
      path: "/api/analytics/event",
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Track analytics event",
      command: () => `/api/analytics/event`,
    },
    update: {
      method: "PUT",
      path: `/api/analytics/update`,
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Update analytics user mapping",
      command: `/api/analytics/update`,
    },
    users: {
      method: "GET",
      path: "/api/analytics/users/week",
      roles: ["ADMIN"],
      description: "Get weekly user analytics",
      command: () => `/api/analytics/users/week`,
    },
    pageviews: {
      method: "GET",
      path: "/api/analytics/pageviews/week",
      roles: ["ADMIN"],
      description: "Get weekly pageview analytics",
      command: () => `/api/analytics/pageviews/week`,
    },
    pageviewsByPage: {
      method: "GET",
      path: "/api/analytics/pageviews/by-page",
      roles: ["ADMIN"],
      description: "Get pageviews by page",
      command: () => `/api/analytics/pageviews/by-page`,
    },
    pageviewsSegments: {
      method: "GET",
      path: "/api/analytics/pageviews/segments",
      roles: ["ADMIN"],
      description: "Get pageviews segments",
      command: () => `/api/analytics/pageviews/segments`,
    },
    visitors: {
      method: "GET",
      path: (range) => `/api/analytics/visitors?range=${range}`,
      roles: ["ADMIN"],
      description: "Get visitor analytics",
      command: (range = "7d") => `/api/analytics/visitors?range=${range}`,
    },
    bounceRate: {
      method: "GET",
      path: (range) => `/api/analytics/bounce-rate?range=${range}`,
      roles: ["ADMIN"],
      description: "Get bounce rate analytics",
      command: (range = "7d") => `/api/analytics/bounce-rate?range=${range}`,
    },
    browser: {
      method: "GET",
      path: "/api/analytics/browser",
      roles: ["ADMIN"],
      description: "Get browser analytics",
      command: () => `/api/analytics/browser`,
    },
    sessionsDevices: {
      method: "GET",
      path: "/api/analytics/sessions/devices",
      roles: ["ADMIN"],
      description: "Get sessions by devices",
      command: () => `/api/analytics/sessions/devices`,
    },
    timeOnPage: {
      method: "GET",
      path: "/api/analytics/timeonpage/week",
      roles: ["ADMIN"],
      description: "Get weekly time on page analytics",
      command: () => `/api/analytics/timeonpage/week`,
    },
    referrers: {
      method: "GET",
      path: "/api/analytics/referrers",
      roles: ["ADMIN"],
      description: "Get referrer analytics",
      command: () => `/api/analytics/referrers`,
    },
    errors: {
      method: "GET",
      path: "/api/analytics/errors",
      roles: ["ADMIN"],
      description: "Get error analytics",
      command: () => `/api/analytics/errors`,
    },
    delete: {
      method: "DELETE",
      path: (id) => `/api/analytics/${id}/delete`,
      roles: ["ADMIN"],
      description: "Delete error analytics",
      command: (id = "99") => `/api/analytics/${id}/delete`,
    },
  },
  aiChat: {
    post: {
      method: "POST",
      path: "/api/ai-chat",
      roles: ["USER", "MEMBER", "ADMIN"],
      description: "Send message to AI chat assistant",
      command: () => "/api/ai-chat",
    },
  },
  metrics: {
    status: {
      method: "GET",
      path: "/api/metrics",
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get application metrics and health status",
      command: () => "/api/metrics",
    },
  },
  artPieceTags: {
    list: {
      method: "GET",
      path: "/api/art-piece-tags",
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get list of art piece tags",
      command: () => "/api/art-piece-tags",
    },
    details: {
      method: "GET",
      path: (id) => `/api/art-piece-tags/${id}`,
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get art piece tag by ID",
      command: (id = "99") => `/api/art-piece-tags/${id}`,
    },
    create: {
      method: "POST",
      path: "/api/art-piece-tags/create",
      roles: ["MEMBER", "ADMIN"],
      description: "Create a new art piece tag",
      command: () => "/api/art-piece-tags/create",
    },
    update: {
      method: "PUT",
      path: (id) => `/api/art-piece-tags/${id}/update`,
      roles: ["MEMBER", "ADMIN"],
      description: "Update art piece tag by ID",
      command: (id = "99") => `/api/art-piece-tags/${id}/update`,
    },
    delete: {
      method: "DELETE",
      path: (id) => `/api/art-piece-tags/${id}/delete`,
      roles: ["MEMBER", "ADMIN"],
      description: "Delete art piece tag by ID",
      command: (id = "99") => `/api/art-piece-tags/${id}/delete`,
    },
    search: {
      method: "GET",
      path: "/api/art-piece-tags/search",
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Search art piece tags",
      command: () => "/api/art-piece-tags/search",
    },
  },
  artPiece: {
    list: {
      method: "GET",
      path: "/api/art-piece",
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get paginated list of art pieces",
      command: () => "/api/art-piece",
      params: [
        "page",
        "limit",
        "search",
        "status",
        "artistId",
        "cityId",
        "stateId",
        "countryId",
        "userId",
        "featured",
        "createdBy",
        "updatedBy",
        "createdAt",
        "updatedAt",
        "sortBy",
        "sortOrder",
      ],
    },
    details: {
      method: "GET",
      path: (id) => `/api/art-piece/${id}`,
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get art piece by ID",
      command: (id = "9999") => `/api/art-piece/${id}`,
    },
    create: {
      method: "POST",
      path: "/api/art-piece/create",
      roles: ["MEMBER", "ADMIN"],
      description: "Create a new art piece",
      command: () => "/api/art-piece/create",
    },
    update: {
      method: "PUT",
      path: (id) => `/api/art-piece/${id}/update`,
      roles: ["MEMBER", "ADMIN"],
      description: "Update an art piece",
      command: (id = "9999") => `/api/art-piece/${id}/update`,
    },
    delete: {
      method: "DELETE",
      path: (id) => `/api/art-piece/${id}/delete`,
      roles: ["MEMBER", "ADMIN"],
      description: "Delete an art piece",
      command: (id = "9999") => `/api/art-piece/${id}/delete`,
    },
    description: {
      method: "POST",
      path: (id) => `/api/art-piece/${id}/description`,
      roles: ["MEMBER", "ADMIN"],
      description: "Generate AI description for art piece",
      command: (id = "9999") => `/api/art-piece/${id}/description`,
    },
    search: {
      method: "GET",
      path: "/api/art-piece/search",
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Search art pieces",
      command: () => "/api/art-piece/search",
      params: [
        "page",
        "limit",
        "search",
        "status",
        "artistId",
        "cityId",
        "stateId",
        "countryId",
        "userId",
        "featured",
        "createdBy",
        "updatedBy",
        "createdAt",
        "updatedAt",
        "sortBy",
        "sortOrder",
      ],
    },
    counts: {
      method: "GET",
      path: (id) => `/api/art-piece/${id}/counts`,
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get art piece view/favorite counts",
      command: (id = "9999") => `/api/art-piece/${id}/counts`,
    },
    reviews: {
      method: "GET",
      path: (id) => `/api/art-piece/${id}/reviews`,
      roles: ["MEMBER", "ADMIN"],
      description: "Get reviews for an art piece",
      command: (id = "9999") => `/api/art-piece/${id}/reviews`,
    },
    updateViewCount: {
      method: "PUT",
      path: (id) => `/api/art-piece/${id}/update-view-count`,
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Update view count for art piece",
      command: (id = "9999") => `/api/art-piece/${id}/update-view-count`,
    },
    status: {
      method: "GET",
      path: (status) => `/api/art-piece/status/${status}`,
      roles: ["MEMBER", "ADMIN"],
      description: "Get art pieces filtered by status",
      command: (status = "ACTIVE") => `/api/art-piece/status/${status}`,
    },
    byCountry: {
      method: "GET",
      path: (country) => `/api/art-piece/explore/${country}`,
      roles: ["USER", "MEMBER", "ADMIN"],
      description: "Explore art pieces by country",
      command: (country = "us") => `/api/art-piece/explore/${country}`,
    },
    byState: {
      method: "GET",
      path: (country, state) => `/api/art-piece/explore/${country}/${state}`,
      roles: ["USER", "MEMBER", "ADMIN"],
      description: "Explore art pieces by state",
      command: (country = "us", state = "oregon") =>
        `/api/art-piece/explore/${country}/${state}`,
    },
    byCity: {
      method: "GET",
      path: (country, state, city) =>
        `/api/art-piece/explore/${country}/${state}/${city}`,
      roles: ["USER", "MEMBER", "ADMIN"],
      description: "Explore art pieces by city",
      command: (country = "us", state = "oregon", city = "portland") =>
        `/api/art-piece/explore/${country}/${state}/${city}`,
    },
    byArtist: {
      method: "GET",
      path: (artistSlug) => `/api/art-piece/artist/${artistSlug}`,
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get all art pieces by artist",
      command: (artistSlug = "test-artist") =>
        `/api/art-piece/artist/${artistSlug}`,
    },
    bySlug: {
      method: "GET",
      path: (artistSlug, slug) => `/api/art-piece/artist/${artistSlug}/${slug}`,
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get art piece by artist slug and piece slug",
      command: (artistSlug = "test-artist", slug = "test-art-piece") =>
        `/api/art-piece/artist/${artistSlug}/${slug}`,
    },
    byViewport: {
      method: "GET",
      path: "/api/art-piece/viewport",
      roles: ["USER", "MEMBER", "ADMIN"],
      description: "Get art pieces within a viewport/bounding box",
      command: () =>
        "/api/art-piece/viewport?swLat=45.5&swLng=-122.7&neLat=45.6&neLng=-122.6&zoom=12",
    },
    staticMap: {
      method: "POST",
      path: (id) => `/api/art-piece/${id}/static-map`,
      roles: ["MEMBER", "ADMIN"],
      description: "create static map for art piece",
      command: (id = "9999") => `/api/art-piece/${id}/static-map`,
    },
    metaDescription: {
      method: "POST",
      path: (id) => `/api/art-piece/${id}/meta-description`,
      roles: ["USER", "MEMBER", "ADMIN"],
      description: "Generate AI-powered meta description for art piece",
      command: (id = "9999") => `/api/art-piece/${id}/meta-description`,
    },
    metaKeywords: {
      method: "POST",
      path: (id) => `/api/art-piece/${id}/meta-keywords`,
      roles: ["USER", "MEMBER", "ADMIN"],
      description: "Generate AI-powered meta keywords for art piece",
      command: (id = "9999") => `/api/art-piece/${id}/meta-keywords`,
    },
  },
  artPieceMaterials: {
    list: {
      method: "GET",
      path: "/api/art-piece-materials",
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get list of art piece materials",
      command: () => "/api/art-piece-materials",
    },
    details: {
      method: "GET",
      path: (id) => `/api/art-piece-materials/${id}`,
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get art piece material by ID",
      command: (id = "99") => `/api/art-piece-materials/${id}`,
    },
    create: {
      method: "POST",
      path: "/api/art-piece-materials/create",
      roles: ["MEMBER", "ADMIN"],
      description: "Create a new art piece material",
      command: () => "/api/art-piece-materials/create",
    },
    update: {
      method: "PUT",
      path: (id) => `/api/art-piece-materials/${id}/update`,
      roles: ["MEMBER", "ADMIN"],
      description: "Update art piece material by ID",
      command: (id = "99") => `/api/art-piece-materials/${id}/update`,
    },
    delete: {
      method: "DELETE",
      path: (id) => `/api/art-piece-materials/${id}/delete`,
      roles: ["MEMBER", "ADMIN"],
      description: "Delete art piece material by ID",
      command: (id = "99") => `/api/art-piece-materials/${id}/delete`,
    },
    search: {
      method: "GET",
      path: "/api/art-piece-materials/search",
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Search art piece materials",
      command: () => "/api/art-piece-materials/search",
    },
  },
  artPieceType: {
    list: {
      method: "GET",
      path: "/api/art-piece-type",
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get list of art piece types",
      command: () => "/api/art-piece-type",
    },
    details: {
      method: "GET",
      path: (id) => `/api/art-piece-type/${id}`,
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get art piece type by ID",
      command: (id = "99") => `/api/art-piece-type/${id}`,
    },
    create: {
      method: "POST",
      path: "/api/art-piece-type/create",
      roles: ["MEMBER", "ADMIN"],
      description: "Create a new art piece type",
      command: () => "/api/art-piece-type/create",
    },
    update: {
      method: "PUT",
      path: (id) => `/api/art-piece-type/${id}/update`,
      roles: ["MEMBER", "ADMIN"],
      description: "Update art piece type by ID",
      command: (id = "99") => `/api/art-piece-type/${id}/update`,
    },
    delete: {
      method: "DELETE",
      path: (id) => `/api/art-piece-type/${id}/delete`,
      roles: ["MEMBER", "ADMIN"],
      description: "Delete art piece type by ID",
      command: (id = "99") => `/api/art-piece-type/${id}/delete`,
    },
    search: {
      method: "GET",
      path: "/api/art-piece-type/search",
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Search art piece types",
      command: () => "/api/art-piece-type/search",
    },
  },
  artist: {
    list: {
      method: "GET",
      path: "/api/artist",
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get paginated list of artists",
      command: () => "/api/artist",
    },
    details: {
      method: "GET",
      path: (id) => `/api/artist/${id}`,
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get artist by ID",
      command: (id = "9999") => `/api/artist/${id}`,
    },
    create: {
      method: "POST",
      path: "/api/artist/create",
      roles: ["MEMBER", "ADMIN"],
      description: "Create a new artist",
      command: () => "/api/artist/create",
    },
    update: {
      method: "PUT",
      path: (id) => `/api/artist/${id}/update`,
      roles: ["USER", "MEMBER", "ADMIN"],
      description: "Update artist by ID",
      command: (id = "9999") => `/api/artist/${id}/update`,
    },
    delete: {
      method: "DELETE",
      path: (id) => `/api/artist/${id}/delete`,
      roles: ["MEMBER", "ADMIN"],
      description: "Delete artist by ID",
      command: (id = "9999") => `/api/artist/${id}/delete`,
    },
    status: {
      method: "GET",
      path: (status) => `/api/artist/status/${status}`,
      roles: ["MEMBER", "ADMIN"],
      description: "Get list of artists by status",
      command: (status = "ACTIVE") => `/api/artist/status/${status}`,
    },
    slug: {
      method: "GET",
      path: (slug) => `/api/artist/slug/${slug}`,
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get artist by slug",
      command: (slug = "test-artist") => `/api/artist/slug/${slug}`,
    },
    counts: {
      method: "GET",
      path: (id) => `/api/artist/${id}/counts`,
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get aggregated counts for an artist",
      command: (id = "9999") => `/api/artist/${id}/counts`,
    },
    biography: {
      method: "POST",
      path: "/api/artist/biography",
      roles: ["MEMBER", "ADMIN"],
      description: "Submit a suggested biography",
      command: () => "/api/artist/biography",
    },
    staticMap: {
      method: "POST",
      path: (id) => `/api/artist/${id}/static-map`,
      roles: ["MEMBER", "ADMIN"],
      description: "Manage artist static map",
      command: (id = "9999") => `/api/artist/${id}/static-map`,
    },
    updateViewCount: {
      method: "PUT",
      path: (id) => `/api/artist/${id}/update-view-count`,
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Update artist view count",
      command: (id = "9999") => `/api/artist/${id}/update-view-count`,
    },
    metaDescription: {
      method: "POST",
      path: (id) => `/api/artist/${id}/meta-description`,
      roles: ["USER", "MEMBER", "ADMIN"],
      description: "Generate AI-powered meta description for artist",
      command: (id = "9999") => `/api/artist/${id}/meta-description`,
    },
    metaKeywords: {
      method: "POST",
      path: (id) => `/api/artist/${id}/meta-keywords`,
      roles: ["USER", "MEMBER", "ADMIN"],
      description: "Generate AI-powered meta keywords for artist",
      command: (id = "9999") => `/api/artist/${id}/meta-keywords`,
    },
  },
  artistLocation: {
    list: {
      method: "GET",
      path: "/api/artist-location",
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get paginated list of artist locations",
      command: () => "/api/artist-location",
    },
    details: {
      method: "GET",
      path: (id) => `/api/artist-location/${id}`,
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get artist location by ID",
      command: (id = "9999") => `/api/artist-location/${id}`,
    },
    create: {
      method: "POST",
      path: "/api/artist-location/create",
      roles: ["MEMBER", "ADMIN"],
      description: "Create a new artist location mapping",
      command: () => "/api/artist-location/create",
    },
    update: {
      method: "PUT",
      path: (id) => `/api/artist-location/${id}/update`,
      roles: ["MEMBER", "ADMIN"],
      description: "Update artist location by ID",
      command: (id = "9999") => `/api/artist-location/${id}/update`,
    },
    delete: {
      method: "DELETE",
      path: (id) => `/api/artist-location/${id}/delete`,
      roles: ["MEMBER", "ADMIN"],
      description: "Delete artist location by ID",
      command: (id = "9999") => `/api/artist-location/${id}/delete`,
    },
    byArtist: {
      method: "GET",
      path: (artistId) => `/api/artist-location/artist/${artistId}`,
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get all locations for a specific artist",
      command: (artistId = "9999") => `/api/artist-location/artist/${artistId}`,
    },
  },
  auth: {
    me: "/api/auth/me",
    login: "/api/auth/login",
    logout: "/api/auth/logout",
    callback: "/api/auth/callback",
  },
  calendar: {
    list: {
      method: "GET",
      path: "/api/calendar",
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get calendar events",
      command: () => `/api/calendar`,
    },
  },
  chat: {
    list: {
      method: "GET",
      path: "/api/chat",
      roles: ["MEMBER", "ADMIN"],
      description: "Get list of chat messages",
      command: () => `/api/chat`,
    },
    details: {
      method: "GET",
      path: (id) => `/api/chat/${id}`,
      roles: ["MEMBER", "ADMIN"],
      description: "Get chat message by ID",
      command: (id = "123") => `/api/chat/${id}`,
    },
    create: {
      method: "POST",
      path: "/api/chat",
      roles: ["MEMBER", "ADMIN"],
      description: "Create a new chat message",
      command: () => `/api/chat`,
    },
    createAlt: {
      method: "POST",
      path: "/api/chat/create",
      roles: ["MEMBER", "ADMIN"],
      description: "Create a new chat message (alternative route)",
      command: () => `/api/chat/create`,
    },
    update: {
      method: "PUT",
      path: (id) => `/api/chat/${id}/update`,
      roles: ["MEMBER", "ADMIN"],
      description: "Update chat message by ID",
      command: (id = "123") => `/api/chat/${id}/update`,
    },
    delete: {
      method: "DELETE",
      path: (id) => `/api/chat/${id}/delete`,
      roles: ["MEMBER", "ADMIN"],
      description: "Delete chat message by ID",
      command: (id = "123") => `/api/chat/${id}/delete`,
    },
  },
  city: {
    list: {
      method: "GET",
      path: "/api/city",
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get list of cities",
      command: () => `/api/city`,
    },
    active: {
      method: "GET",
      path: "/api/city/active/",
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get list of active cities",
      command: () => `/api/city/active/`,
    },
    details: {
      method: "GET",
      path: (id) => `/api/city/${id}`,
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get city details by ID",
      command: (id = "123") => `/api/city/${id}`,
    },
    update: {
      method: "PUT",
      path: (id) => `/api/city/${id}/update`,
      roles: ["ADMIN"],
      description: "Update city by ID",
      command: (id = "123") => `/api/city/${id}/update`,
    },
    delete: {
      method: "DELETE",
      path: (id) => `/api/city/${id}/delete`,
      roles: ["ADMIN"],
      description: "Delete city by ID",
      command: (id = "123") => `/api/city/${id}/delete`,
    },
    create: {
      method: "POST",
      path: `/api/city/create`,
      roles: ["ADMIN"],
      description: "Create a new city",
      command: () => `/api/city/create`,
    },
  },
  contact: {
    list: {
      method: "GET",
      path: "/api/contact",
      roles: ["ADMIN"],
      description: "Get list of contact messages",
      command: () => `/api/contact`,
    },
    details: {
      method: "GET",
      path: (id) => `/api/contact/${id}`,
      roles: ["ADMIN"],
      description: "Get contact us message by ID",
      command: (id) => `/api/contact/${id}`,
    },
    create: {
      method: "POST",
      path: "/api/contact/create",
      roles: ["public", "USER", "ADMIN"],
      description: "Create a new contact us message",
      command: () => `/api/contact/create`,
    },
    update: {
      method: "PUT",
      path: (id) => `/api/contact/${id}/update`,
      roles: ["ADMIN"],
      description: "Update contact us message by ID",
      command: (id) => `/api/contact/${id}/update`,
    },
    delete: {
      method: "DELETE",
      path: (id) => `/api/contact/${id}/delete`,
      roles: ["ADMIN"],
      description: "Delete contact us message by ID",
      command: (id) => `/api/contact/${id}/delete`,
    },
  },
  country: {
    list: {
      method: "GET",
      path: "/api/country",
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get list of countries",
      command: () => `/api/country`,
    },
    details: {
      method: "GET",
      path: (id) => `/api/country/${id}`,
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get country by ID",
      command: (id = "123") => `/api/country/${id}`,
    },
    create: {
      method: "POST",
      path: "/api/country/create",
      roles: ["ADMIN"],
      description: "Create a new country",
      command: () => `/api/country/create`,
    },
    update: {
      method: "PUT",
      path: (id) => `/api/country/${id}/update`,
      roles: ["ADMIN"],
      description: "Update country by ID",
      command: (id = "123") => `/api/country/${id}/update`,
    },
    delete: {
      method: "DELETE",
      path: (id) => `/api/country/${id}/delete`,
      roles: ["ADMIN"],
      description: "Delete country by ID",
      command: (id = "123") => `/api/country/${id}/delete`,
    },
    states: {
      method: "GET",
      path: (id) => `/api/country/${id}/states`,
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get states for a country",
      command: (id = "123") => `/api/country/${id}/states`,
    },
    slug: {
      method: "GET",
      path: (slug) => `/api/country/slug/${slug}`,
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get country by slug",
      command: (slug = "united-states") => `/api/country/slug/${slug}`,
    },
  },
  email: {
    list: {
      method: "GET",
      path: "/api/email",
      roles: ["USER", "MEMBER", "ADMIN"],
      description: "Get list of emails",
      command: () => `/api/email`,
    },
    details: {
      method: "GET",
      path: (id) => `/api/email/${id}`,
      roles: ["USER", "MEMBER", "ADMIN"],
      description: "Get email by ID",
      command: (id = "123") => `/api/email/${id}`,
    },
    create: {
      method: "POST",
      path: "/api/email/create",
      roles: ["ADMIN"],
      description: "Create a new email",
      command: () => `/api/email/create`,
    },
    update: {
      method: "PUT",
      path: (id) => `/api/email/${id}/update`,
      roles: ["ADMIN"],
      description: "Update email by ID",
      command: (id = "123") => `/api/email/${id}/update`,
    },
    delete: {
      method: "DELETE",
      path: (id) => `/api/email/${id}/delete`,
      roles: ["ADMIN"],
      description: "Delete email by ID",
      command: (id = "123") => `/api/email/${id}/delete`,
    },
  },
  emailTemplate: {
    list: {
      method: "GET",
      path: "/api/email-templates",
      roles: ["ADMIN"],
      description: "Get list of email templates",
      command: () => `/api/email-templates`,
    },
    details: {
      method: "GET",
      path: (id) => `/api/email-templates/${id}`,
      roles: ["ADMIN"],
      description: "Get email template by ID",
      command: (id = "1") => `/api/email-templates/${id}`,
    },
    create: {
      method: "POST",
      path: "/api/email-templates/create",
      roles: ["ADMIN"],
      description: "Create a new email template",
      command: () => `/api/email-templates/create`,
    },
    update: {
      method: "PUT",
      path: (id) => `/api/email-templates/${id}/update`,
      roles: ["ADMIN"],
      description: "Update email template by ID",
      command: (id = "1") => `/api/email-templates/${id}/update`,
    },
    delete: {
      method: "DELETE",
      path: (id) => `/api/email-templates/${id}/delete`,
      roles: ["ADMIN"],
      description: "Delete email template by ID",
      command: (id = "1") => `/api/email-templates/${id}/delete`,
    },
    preview: {
      method: "POST",
      path: (id) => `/api/email-templates/${id}/preview`,
      roles: ["ADMIN"],
      description: "Preview email template with sample data",
      command: (id = "1") => `/api/email-templates/${id}/preview`,
    },
    test: {
      method: "POST",
      path: (id) => `/api/email-templates/${id}/test`,
      roles: ["ADMIN"],
      description: "Send test email using template",
      command: (id = "1") => `/api/email-templates/${id}/test`,
    },
  },
  friend: {
    list: {
      method: "GET",
      path: "/api/friend",
      roles: ["USER", "ADMIN"],
      description: "Get paginated list of friend relationships",
      command: () => `/api/friend`,
    },
    // TODO: Additional friend endpoints (create/update/delete) use composite IDs and will be added when routes are implemented
  },
  geoip: {
    location: `https://pro.ip-api.com/json/?key=${CONFIG.geoIPKey}`,
    ip: "https://www.cityartwalks.com/api/ip/",
  },
  image: {
    list: {
      method: "GET",
      path: "/api/image",
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get list of images",
      command: () => `/api/image`,
    },
    details: {
      method: "GET",
      path: (id) => `/api/image/${id}`,
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get image by ID",
      command: (id = "9999") => `/api/image/${id}`,
    },
    create: {
      method: "POST",
      path: "/api/image/create",
      roles: ["MEMBER", "USER", "ADMIN"],
      description: "Create a new image",
      command: () => `/api/image/create`,
    },
    upload: {
      method: "POST",
      path: "/api/image/upload",
      roles: ["MEMBER", "USER", "ADMIN"],
      description: "Upload image file to Vercel Blob storage",
      command: () => `/api/image/upload`,
    },
    update: {
      method: "PUT",
      path: (id) => `/api/image/${id}/update`,
      roles: ["MEMBER", "USER", "ADMIN"],
      description: "Update image by ID",
      command: (id = "9999") => `/api/image/${id}/update`,
    },
    delete: {
      method: "DELETE",
      path: (id) => `/api/image/${id}/delete`,
      roles: ["MEMBER", "USER", "ADMIN"],
      description: "Delete image by ID",
      command: (id = "9999") => `/api/image/${id}/delete`,
    },
    flagged: {
      method: "GET",
      path: "/api/image/flagged",
      roles: ["ADMIN"],
      description: "Get paginated list of flagged images for moderation",
      command: () => "/api/image/flagged?page=1&limit=10",
    },
    moderate: {
      method: "POST",
      path: "/api/image/moderate",
      roles: ["ADMIN"],
      description:
        "Moderate images (approve/remove) with support for bulk operations",
      command: () => "/api/image/moderate",
    },
  },
  indexNowSubmission: {
    list: {
      method: "GET",
      path: "/api/index-now-submission",
      roles: ["ADMIN"],
      description: "Get paginated list of IndexNow submissions",
      command: () => "/api/index-now-submission?page=1&limit=10",
    },
    details: {
      method: "GET",
      path: (id) => `/api/index-now-submission/${id}`,
      roles: ["ADMIN"],
      description: "Get IndexNow submission by ID",
      command: (id = "9999") => `/api/index-now-submission/${id}`,
    },
    create: {
      method: "POST",
      path: "/api/index-now-submission/create",
      roles: ["ADMIN"],
      description: "Create a new IndexNow submission",
      command: () => "/api/index-now-submission/create",
    },
    update: {
      method: "PUT",
      path: (id) => `/api/index-now-submission/${id}/update`,
      roles: ["ADMIN"],
      description: "Update IndexNow submission by ID",
      command: (id = "9999") => `/api/index-now-submission/${id}/update`,
    },
    delete: {
      method: "DELETE",
      path: (id) => `/api/index-now-submission/${id}/delete`,
      roles: ["ADMIN"],
      description: "Delete IndexNow submission by ID",
      command: (id = "9999") => `/api/index-now-submission/${id}/delete`,
    },
    process: {
      method: "POST",
      path: (id) => `/api/index-now-submission/${id}/process`,
      roles: ["ADMIN"],
      description: "Manually process IndexNow submission by ID",
      command: (id = "9999") => `/api/index-now-submission/${id}/process`,
    },
    stats: {
      method: "GET",
      path: () => "/api/index-now-submission/stats",
      roles: ["ADMIN"],
      description: "Get IndexNow submission statistics",
      command: () => `/api/index-now-submission/stats`,
    },
    clearQueue: {
      method: "POST",
      path: "/api/index-now-submission/clear-queue",
      roles: ["ADMIN"],
      description: "Clear all pending IndexNow submissions from the queue",
      command: () => "/api/index-now-submission/clear-queue",
    },
    processQueue: {
      method: "POST",
      path: "/api/index-now-submission/process",
      roles: ["ADMIN"],
      description: "Process all pending IndexNow submissions in the queue",
      command: () => "/api/index-now-submission/process",
    },
    retryFailed: {
      method: "POST",
      path: "/api/index-now-submission/retry-failed",
      roles: ["ADMIN"],
      description: "Retry all failed IndexNow submissions",
      command: () => "/api/index-now-submission/retry-failed",
    },
  },
  location: {
    list: {
      method: "GET",
      path: "/api/location",
      roles: ["USER", "MEMBER", "ADMIN"],
      description: "Get list of locations",
      command: () => `/api/location`,
    },
    country: {
      method: "GET",
      path: (country) => `/api/location/${country}`,
      roles: ["USER", "MEMBER", "ADMIN"],
      description: "Get location by country slug",
      command: (country = "us") => `/api/location/${country}`,
    },
    region: {
      method: "GET",
      path: (country, region) => `/api/location/${country}/${region}`,
      roles: ["USER", "MEMBER", "ADMIN"],
      description: "Get location by country and region",
      command: (country = "us", region = "oregon") =>
        `/api/location/${country}/${region}`,
    },
    city: {
      method: "GET",
      path: (country, region, city) =>
        `/api/location/${country}/${region}/${city}`,
      roles: ["USER", "MEMBER", "ADMIN"],
      description: "Get location by country, region, and city",
      command: (
        country = "united-states",
        region = "oregon",
        city = "portland",
      ) => `/api/location/${country}/${region}/${city}`,
    },
  },
  map: {
    static: {
      create: {
        method: "POST",
        path: "/api/map/static",
        roles: ["MEMBER", "ADMIN"],
        description: "Create a new static map",
        command: () => `/api/map/static`,
      },
    },
  },
  notification: {
    list: {
      method: "GET",
      path: "/api/notification",
      roles: ["USER", "MEMBER", "ADMIN"],
      description: "Get list of notifications",
      command: () => `/api/notification`,
    },
    details: {
      method: "GET",
      path: (id) => `/api/notification/${id}`,
      roles: ["USER", "MEMBER", "ADMIN"],
      description: "Get notification by ID",
      command: (id = "123") => `/api/notification/${id}`,
    },
    create: {
      method: "POST",
      path: "/api/notification/create",
      roles: ["USER", "MEMBER", "ADMIN"],
      description: "Create a new notification",
      command: () => `/api/notification/create`,
    },
    update: {
      method: "PUT",
      path: (id) => `/api/notification/${id}/update`,
      roles: ["USER", "MEMBER", "ADMIN"],
      description: "Update notification by ID",
      command: (id = "123") => `/api/notification/${id}/update`,
    },
    markRead: {
      method: "PUT",
      path: (id) => `/api/notification/${id}/mark-read`,
      roles: ["USER", "MEMBER", "ADMIN"],
      description: "Mark a notification as read",
      command: (id = "123") => `/api/notification/${id}/mark-read`,
    },
    markAllRead: {
      method: "PUT",
      path: "/api/notification/mark-all-read",
      roles: ["USER", "MEMBER", "ADMIN"],
      description: "Mark all notifications as read for the authenticated user",
      command: () => "/api/notification/mark-all-read",
    },
    delete: {
      method: "DELETE",
      path: (id) => `/api/notification/${id}/delete`,
      roles: ["USER", "MEMBER", "ADMIN"],
      description: "Delete notification by ID",
      command: (id = "123") => `/api/notification/${id}/delete`,
    },
    user: {
      method: "GET",
      path: (userId) => `/api/notification/user/${userId}`,
      roles: ["USER", "MEMBER", "ADMIN"],
      description: "Get notifications for a user",
      command: (userId = "123") => `/api/notification/user/${userId}`,
    },
  },
  notificationDelivery: {
    list: {
      method: "GET",
      path: "/api/notification-delivery",
      roles: ["ADMIN"],
      description: "Get paginated notification delivery records",
      command: () => `/api/notification-delivery?page=0&limit=20`,
    },
    details: {
      method: "GET",
      path: (deliveryId) => `/api/notification-delivery/${deliveryId}`,
      roles: ["ADMIN"],
      description: "Get delivery record by ID",
      command: (deliveryId = "123") =>
        `/api/notification-delivery/${deliveryId}`,
    },
    stats: {
      method: "GET",
      path: "/api/notification-delivery/stats",
      roles: ["ADMIN"],
      description: "Get delivery statistics",
      command: () => `/api/notification-delivery/stats`,
    },
    retry: {
      method: "POST",
      path: (deliveryId) => `/api/notification-delivery/${deliveryId}/retry`,
      roles: ["ADMIN"],
      description: "Retry failed delivery",
      command: (deliveryId = "123") =>
        `/api/notification-delivery/${deliveryId}/retry`,
    },
  },
  path: {
    list: {
      method: "GET",
      path: "/api/path",
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get list of paths",
      command: () => `/api/path`,
    },
    details: {
      method: "GET",
      path: (id) => `/api/path/${id}`,
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get path by ID",
      command: (id = "99") => `/api/path/${id}`,
    },
    create: {
      method: "POST",
      path: "/api/path",
      roles: ["MEMBER", "ADMIN"],
      description: "Create a new path",
      command: () => `/api/path/create`,
    },
    update: {
      method: "PUT",
      path: (id) => `/api/path/${id}`,
      roles: ["MEMBER", "ADMIN"],
      description: "Update path by ID",
      command: (id = "9999") => `/api/path/${id}/update`,
    },
    delete: {
      method: "DELETE",
      path: (id) => `/api/path/${id}`,
      roles: ["MEMBER", "ADMIN"],
      description: "Delete path by ID",
      command: (id = "9999") => `/api/path/${id}/delete`,
    },
    description: {
      create: {
        method: "POST",
        path: "/api/path/description",
        roles: ["MEMBER", "ADMIN"],
        description: "Create a new path description",
        command: (id = "9999") => `/api/path/${id}/description`,
      },
    },
    updateViewCount: {
      method: "PUT",
      path: (id) => `/api/path/${id}/view-count`,
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Update view count for a path",
      command: (id = "9999") => `/api/path/${id}/view-count`,
    },
    counts: {
      method: "GET",
      path: (id) => `/api/path/${id}/counts`,
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get view counts for a path",
      command: (id = "9999") => `/api/path/${id}/counts`,
    },
    zoom: {
      method: "GET",
      path: "/api/path/zoom",
      roles: ["USER", "MEMBER", "ADMIN"],
      description: "Get available zoom levels for paths",
      command: () => `/api/path/zoom`,
    },
    type: {
      method: "GET",
      path: "/api/path/type",
      roles: ["USER", "MEMBER", "ADMIN"],
      description: "Get available path types",
      command: () => `/api/path/type`,
    },
    mapType: {
      method: "GET",
      path: "/api/path/type/map",
      roles: ["USER", "MEMBER", "ADMIN"],
      description: "Get available map types for paths",
      command: () => `/api/path/type/map`,
    },
  },
  post: {
    list: {
      method: "GET",
      path: "/api/post",
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get paginated list of posts",
      command: () => `/api/post`,
    },
    details: {
      method: "GET",
      path: (id) => `/api/post/${id}`,
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get post by ID",
      command: (id = "123") => `/api/post/${id}`,
    },
    create: {
      method: "POST",
      path: "/api/post/create",
      roles: ["ADMIN"],
      description: "Create a new post",
      command: () => `/api/post/create`,
    },
    update: {
      method: "PUT",
      path: "/api/post/[id]/update",
      roles: ["ADMIN"],
      description: "Update post by ID",
      command: (id = "123") => `/api/post/${id}/update`,
    },
    delete: {
      method: "DELETE",
      path: "/api/post/[id]/delete",
      roles: ["ADMIN"],
      description: "Delete post by ID",
      command: (id = "123") => `/api/post/${id}/delete`,
    },
    latest: {
      method: "GET",
      path: "/api/post/latest",
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get latest posts",
      command: () => `/api/post/latest`,
    },
    search: {
      method: "GET",
      path: "/api/post/search",
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Search posts",
      command: () => `/api/post/search`,
    },
    bySlug: {
      method: "GET",
      path: "/api/post/slug/[slug]",
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get post by slug",
      command: (slug = "sample-post") => `/api/post/slug/${slug}`,
    },
    byCategory: {
      method: "GET",
      path: "/api/post/category/[category]",
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get posts by category",
      command: (category = "news") => `/api/post/category/${category}`,
    },
    contentAssistance: {
      method: "POST",
      path: "/api/post/content-assistance",
      roles: ["MEMBER", "ADMIN"],
      description:
        "Generate AI-powered complete blog post package (content, excerpt, SEO title, meta description)",
      command: () => `/api/post/content-assistance`,
    },
  },
  comment: {
    list: {
      method: "GET",
      path: "/api/comment",
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get paginated comments for a post",
      command: (postId = "123") => `/api/comment?postId=${postId}`,
    },
    details: {
      method: "GET",
      path: "/api/comment/[id]",
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get comment by ID",
      command: (id = "456") => `/api/comment/${id}`,
    },
    create: {
      method: "POST",
      path: "/api/comment/create",
      roles: ["MEMBER", "ADMIN"],
      description: "Create a new comment",
      command: () => `/api/comment/create`,
    },
    update: {
      method: "PUT",
      path: "/api/comment/[id]/update",
      roles: ["MEMBER", "ADMIN"],
      description: "Update comment (own comment or ADMIN)",
      command: (id = "456") => `/api/comment/${id}/update`,
    },
    delete: {
      method: "DELETE",
      path: "/api/comment/[id]/delete",
      roles: ["MEMBER", "ADMIN"],
      description: "Delete comment (own comment or ADMIN)",
      command: (id = "456") => `/api/comment/${id}/delete`,
    },
    byPost: {
      method: "GET",
      path: "/api/comment/post/[postId]",
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get all comments for a specific post",
      command: (postId = "123") => `/api/comment/post/${postId}`,
    },
    replies: {
      method: "GET",
      path: "/api/comment/[id]/replies",
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get replies for a comment",
      command: (id = "456") => `/api/comment/${id}/replies`,
    },
  },
  product: {
    list: {
      method: "GET",
      path: "/api/product/list",
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get paginated list of products",
      command: () => `/api/product/list`,
    },
    details: {
      method: "GET",
      path: "/api/product/details",
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get product details by ID or slug",
      command: (id) => `/api/product/details?id=${id}`,
    },
    create: {
      method: "POST",
      path: "/api/product/create",
      roles: ["ADMIN"],
      description: "Create a new product",
      command: () => `/api/product/create`,
    },
    update: {
      method: "PUT",
      path: "/api/product/[id]/update",
      roles: ["ADMIN"],
      description: "Update product by ID",
      command: (id) => `/api/product/${id}/update`,
    },
    delete: {
      method: "DELETE",
      path: "/api/product/[id]/delete",
      roles: ["ADMIN"],
      description: "Delete product by ID",
      command: (id) => `/api/product/${id}/delete`,
    },
    search: {
      method: "GET",
      path: "/api/product/search",
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Search products",
      command: () => `/api/product/search`,
    },
    bySlug: {
      method: "GET",
      path: "/api/product/slug/[slug]",
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get product by slug",
      command: (slug) => `/api/product/slug/${slug}`,
    },
    byCategory: {
      method: "GET",
      path: "/api/product/category/[category]",
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get products by category",
      command: (category) => `/api/product/category/${category}`,
    },
    featured: {
      method: "GET",
      path: "/api/product/featured",
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get featured products",
      command: () => `/api/product/featured`,
    },
    digital: {
      method: "GET",
      path: "/api/product/digital",
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get digital products",
      command: () => `/api/product/digital`,
    },
    inventory: {
      method: "PUT",
      path: "/api/product/[id]/inventory",
      roles: ["ADMIN"],
      description: "Update product inventory",
      command: (id) => `/api/product/${id}/inventory`,
    },
  },
  review: {
    list: {
      method: "GET",
      path: "/api/review",
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get list of reviews",
      command: () => `/api/review`,
    },
    details: {
      method: "GET",
      path: (id) => `/api/review/${id}`,
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get review by ID",
      command: (id = "9999") => `/api/review/${id}`,
    },
    create: {
      method: "POST",
      path: "/api/review/create",
      roles: ["MEMBER", "ADMIN"],
      description: "Create a new review with AI moderation",
      command: () => `/api/review/create`,
    },
    update: {
      method: "PUT",
      path: (id) => `/api/review/${id}/update`,
      roles: ["MEMBER", "ADMIN"],
      description: "Update review by ID with re-moderation",
      command: (id = "9999") => `/api/review/${id}/update`,
    },
    delete: {
      method: "DELETE",
      path: (id) => `/api/review/${id}/delete`,
      roles: ["MEMBER", "ADMIN"],
      description: "Soft delete review by ID",
      command: (id = "9999") => `/api/review/${id}/delete`,
    },
    flag: {
      method: "POST",
      path: (id) => `/api/review/${id}/flag`,
      roles: ["USER", "MEMBER", "ADMIN"],
      description: "Flag review for moderation (content owners only)",
      command: (id = "9999") => `/api/review/${id}/flag`,
    },
    stats: {
      method: "GET",
      path: (entityType, entityId) =>
        `/api/review/stats/${entityType}/${entityId}`,
      roles: ["public"],
      description: "Get review statistics for entity",
      command: (entityType = "ART_PIECE", entityId = "123") =>
        `/api/review/stats/${entityType}/${entityId}`,
    },
    moderation: {
      method: "GET",
      path: "/api/review/moderation",
      roles: ["ADMIN"],
      description: "Get reviews requiring moderation",
      command: () => `/api/review/moderation`,
    },
    moderate: {
      method: "PUT",
      path: (id) => `/api/review/${id}/moderate`,
      roles: ["ADMIN"],
      description: "Make admin moderation decision",
      command: (id = "9999") => `/api/review/${id}/moderate`,
    },
    history: {
      method: "GET",
      path: (id) => `/api/review/${id}/history`,
      roles: ["ADMIN"],
      description: "Get review audit history",
      command: (id = "9999") => `/api/review/${id}/history`,
    },
    override: {
      method: "POST",
      path: (id) => `/api/review/${id}/override`,
      roles: ["ADMIN"],
      description: "Record manual override of AI moderation decision",
      command: (id = "9999") => `/api/review/${id}/override`,
    },
    retryAi: {
      method: "POST",
      path: (id) => `/api/review/${id}/retry-ai`,
      roles: ["ADMIN"],
      description: "Retry AI moderation for review",
      command: (id = "9999") => `/api/review/${id}/retry-ai`,
    },
    owner: {
      content: {
        method: "GET",
        path: "/api/review/owner/content",
        roles: ["MEMBER", "ADMIN"],
        description: "Get content owned by authenticated user",
        command: () => `/api/review/owner/content`,
      },
      reviews: {
        method: "GET",
        path: "/api/review/owner/reviews",
        roles: ["MEMBER", "ADMIN"],
        description: "Get reviews for content owned by authenticated user",
        command: () => `/api/review/owner/reviews`,
      },
      stats: {
        method: "GET",
        path: "/api/review/owner/stats",
        roles: ["MEMBER", "ADMIN"],
        description:
          "Get review statistics for content owned by authenticated user",
        command: () => `/api/review/owner/stats`,
      },
      bulkFlag: {
        method: "POST",
        path: "/api/review/owner/bulk-flag",
        roles: ["MEMBER", "ADMIN"],
        description:
          "Bulk flag reviews for content owned by authenticated user",
        command: () => `/api/review/owner/bulk-flag`,
      },
    },
  },
  search: {
    homepage: {
      method: "GET",
      path: "/api/search",
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get search results for homepage",
      command: () => `/api/search`,
    },
  },
  state: {
    list: {
      method: "GET",
      path: "/api/state",
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get paginated list of states",
      command: () => `/api/state`,
    },
    details: {
      method: "GET",
      path: (id) => `/api/state/${id}`,
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get state by ID",
      command: (id = "1") => `/api/state/${id}`,
    },
    create: {
      method: "POST",
      path: "/api/state/create",
      roles: ["ADMIN"],
      description: "Create a new state",
      command: () => `/api/state/create`,
    },
    update: {
      method: "PUT",
      path: (id) => `/api/state/${id}/update`,
      roles: ["USER", "ADMIN"],
      description: "Update state by ID",
      command: (id = "1") => `/api/state/${id}/update`,
    },
    delete: {
      method: "DELETE",
      path: (id) => `/api/state/${id}/delete`,
      roles: ["ADMIN"],
      description: "Delete state by ID",
      command: (id = "1") => `/api/state/${id}/delete`,
    },
    cities: {
      method: "GET",
      path: (id) => `/api/state/${id}/cities`,
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Get cities for a state",
      command: (id = "1") => `/api/state/${id}/cities`,
    },
  },
  stripe: {
    checkout: {
      method: "POST",
      path: `/api/stripe/checkout`,
      roles: ["USER", "MEMBER", "ADMIN"],
      description: "Stripe Checkout",
      command: `/api/stripe/checkout`,
    },
    invoices: {
      method: "GET",
      path: "/api/stripe/invoices",
      roles: ["USER", "MEMBER", "ADMIN"],
      description: "Get user invoices from Stripe",
      command: () => "/api/stripe/invoices",
    },
  },
  user: {
    list: {
      method: "GET",
      path: "/api/user",
      roles: ["ADMIN"],
      description: "Get list of users with pagination and filtering",
      command: () => `/api/user`,
    },
    create: {
      method: "POST",
      path: "/api/user/create",
      roles: ["USER", "MEMBER", "ADMIN"],
      description: "Create a new user (main endpoint)",
      command: () => `/api/user/create`,
    },
    details: {
      method: "GET",
      path: (id) => `/api/user/${id}`,
      roles: ["USER", "MEMBER", "ADMIN"],
      description: "Get user by ID",
      command: (id = "1") => `/api/user/${id}`,
    },
    update: {
      method: "PUT",
      path: (id) => `/api/user/${id}/update`,
      roles: ["USER", "MEMBER", "ADMIN"],
      description: "Update user by ID",
      command: (id = "1") => `/api/user/${id}/update`,
    },
    updateCoverImage: {
      method: "PUT",
      path: (id) => `/api/user/${id}/update/cover-image`,
      roles: ["USER", "MEMBER", "ADMIN"],
      description: "Update user cover image by ID",
      command: (id = "1") => `/api/user/${id}/update/cover-image`,
    },
    updateProfileImage: {
      method: "PUT",
      path: (id) => `/api/user/${id}/update/profile-image`,
      roles: ["USER", "MEMBER", "ADMIN"],
      description: "Update user profile image by ID",
      command: (id = "1") => `/api/user/${id}/update/profile-image`,
    },
    delete: {
      method: "DELETE",
      path: (id) => `/api/user/${id}/delete`,
      roles: ["ADMIN"],
      description: "Delete user by ID",
      command: (id = "1") => `/api/user/${id}/delete`,
    },
    email: {
      method: "GET",
      path: (email) => `/api/user/email/${email}`,
      roles: ["ADMIN"],
      description: "Get user by email",
      command: (email = "jaimie.garner@pdxartwalks.com") =>
        `/api/user/email/${email}`,
    },
    lastLogin: {
      method: "PUT",
      path: (id) => `/api/user/${id}/last-login`,
      roles: ["USER", "MEMBER", "ADMIN"],
      description: "Update user last login timestamp",
      command: (id = "1") => `/api/user/${id}/last-login`,
    },
    authSub: {
      method: "GET",
      path: (sub) => `/api/user/auth/${sub}`,
      roles: ["USER", "MEMBER", "ADMIN"],
      description: "Resolve Auth0 user sub to internal user ID",
      command: (sub = "auth0|6865e4c37c9a087c469ca93b") =>
        `/api/user/auth/${sub}`,
    },
    avatar: {
      method: "GET",
      path: (id) => `/api/user/${id}/avatar`,
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Fetches the users name and avatar",
      command: (id = "1") => `/api/user/${id}/avatar`,
    },
    publicProfile: {
      method: "GET",
      path: (id) => `/api/user/${id}/public-profile`,
      roles: ["public", "USER", "MEMBER", "ADMIN"],
      description: "Fetches public profile data for member profiles",
      command: (id = "1") => `/api/user/${id}/public-profile`,
    },
  },
  userFavoriteArtPiece: {
    list: {
      method: "GET",
      path: "/api/user-favorite-art-piece",
      roles: ["MEMBER", "ADMIN"], // Only admins see all user favorites
      description: "Get list of user favorite art pieces",
      command: () => `/api/user-favorite-art-piece`,
    },
    details: {
      method: "GET",
      path: (id) => `/api/user-favorite-art-piece/${id}`,
      roles: ["USER", "MEMBER", "ADMIN"], // Users can check their own favorites
      description: "Get user favorite art piece by ID",
      command: (id = "123") => `/api/user-favorite-art-piece/${id}`,
    },
    create: {
      method: "POST",
      path: "/api/user-favorite-art-piece",
      roles: ["USER", "MEMBER", "ADMIN"], // Users can add to their favorites
      description: "Create a new user favorite art piece",
      command: () => `/api/user-favorite-art-piece`,
    },
    update: {
      method: "PUT",
      path: (id) => `/api/user-favorite-art-piece/${id}`,
      roles: ["USER", "MEMBER", "ADMIN"], // Users can modify their favorites
      description: "Update user favorite art piece by ID",
      command: (id = "123") => `/api/user-favorite-art-piece/${id}`,
    },
    delete: {
      method: "DELETE",
      path: (id) => `/api/user-favorite-art-piece/${id}`,
      roles: ["USER", "MEMBER", "ADMIN"], // Users can remove from their favorites
      description: "Delete user favorite art piece by ID",
      command: (id = "123") => `/api/user-favorite-art-piece/${id}`,
    },
    user: {
      method: "GET",
      path: (userId) => `/api/user-favorite-art-piece/user/${userId}`,
      roles: ["USER", "MEMBER", "ADMIN"],
      description: "Get user favorite art pieces for a specific user",
      command: (userId = "123") =>
        `/api/user-favorite-art-piece/user/${userId}`,
    },
    toggle: {
      method: "POST",
      path: "/api/user-favorite-art-piece/toggle",
      roles: ["USER", "MEMBER", "ADMIN"],
      description: "Toggle user favorite art piece status",
      command: () => `/api/user-favorite-art-piece/toggle`,
    },
    userArtPieceFavorite: {
      method: "GET",
      path: (userId, artPieceId) =>
        `/api/user-favorite-art-piece/user/${userId}/art-piece/${artPieceId}`,
      roles: ["USER", "MEMBER", "ADMIN"],
      description: "Check if user has favorited specific art piece",
      command: (userId = "123", artPieceId = "456") =>
        `/api/user-favorite-art-piece/user/${userId}/art-piece/${artPieceId}`,
    },
  },
  userFavoriteArtist: {
    list: {
      method: "GET",
      path: "/api/user-favorite-artist",
      roles: ["MEMBER", "ADMIN"],
      description: "Get paginated list of user favorite artists",
      command: () => `/api/user-favorite-artist`,
    },
    details: {
      method: "GET",
      path: "/api/user-favorite-artist/[id]",
      roles: ["MEMBER", "ADMIN"],
      description: "Get user favorite artist by ID",
      command: (id) => `/api/user-favorite-artist/${id}`,
    },
    create: {
      method: "POST",
      path: "/api/user-favorite-artist/create",
      roles: ["MEMBER", "ADMIN"],
      description: "Create new user favorite artist",
      command: () => `/api/user-favorite-artist/create`,
    },
    update: {
      method: "PUT",
      path: "/api/user-favorite-artist/[id]/update",
      roles: ["MEMBER", "ADMIN"],
      description: "Update user favorite artist",
      command: (id) => `/api/user-favorite-artist/${id}/update`,
    },
    delete: {
      method: "DELETE",
      path: "/api/user-favorite-artist/[id]/delete",
      roles: ["MEMBER", "ADMIN"],
      description: "Delete user favorite artist",
      command: (id) => `/api/user-favorite-artist/${id}/delete`,
    },
    userFavorites: {
      method: "GET",
      path: "/api/user-favorite-artist/user/[userId]",
      roles: ["MEMBER", "ADMIN"],
      description: "Get all favorite artists for specific user",
      command: (userId) => `/api/user-favorite-artist/user/${userId}`,
    },
    userArtistFavorite: {
      method: "GET",
      path: "/api/user-favorite-artist/user/[userId]/artist/[artistId]",
      roles: ["MEMBER", "ADMIN"],
      description: "Check if user has favorited specific artist",
      command: (userId, artistId) =>
        `/api/user-favorite-artist/user/${userId}/artist/${artistId}`,
    },
    toggleUserArtistFavorite: {
      method: "POST",
      path: "/api/user-favorite-artist/user/[userId]/artist/[artistId]",
      roles: ["MEMBER", "ADMIN"],
      description: "Toggle artist favorite for user",
      command: (userId, artistId) =>
        `/api/user-favorite-artist/user/${userId}/artist/${artistId}`,
    },
    toggle: {
      method: "POST",
      path: "/api/user-favorite-artist/toggle",
      roles: ["MEMBER", "ADMIN"],
      description: "Toggle user favorite artist status",
      command: () => `/api/user-favorite-artist/toggle`,
    },
  },
  userFavoriteImage: {
    list: {
      method: "GET",
      path: "/api/user-favorite-image",
      roles: ["MEMBER", "ADMIN"],
      description: "Get list of user favorite images",
      command: () => `/api/user-favorite-image`,
    },
    details: {
      method: "GET",
      path: (id) => `/api/user-favorite-image/${id}`,
      roles: ["MEMBER", "ADMIN"],
      description: "Get user favorite image by composite ID",
      command: (id = "1-2") => `/api/user-favorite-image/${id}`,
    },
    create: {
      method: "POST",
      path: "/api/user-favorite-image",
      roles: ["MEMBER", "ADMIN"],
      description: "Create user favorite image",
      command: () => `/api/user-favorite-image`,
    },
    createAlt: {
      method: "POST",
      path: "/api/user-favorite-image/create",
      roles: ["MEMBER", "ADMIN"],
      description: "Create user favorite image (alternative)",
      command: () => `/api/user-favorite-image/create`,
    },
    update: {
      method: "PUT",
      path: (id) => `/api/user-favorite-image/${id}/update`,
      roles: ["MEMBER", "ADMIN"],
      description: "Update user favorite image",
      command: (id = "1-2") => `/api/user-favorite-image/${id}/update`,
    },
    delete: {
      method: "DELETE",
      path: (id) => `/api/user-favorite-image/${id}/delete`,
      roles: ["MEMBER", "ADMIN"],
      description: "Delete user favorite image",
      command: (id = "1-2") => `/api/user-favorite-image/${id}/delete`,
    },
    userFavorites: {
      method: "GET",
      path: (userId) => `/api/user-favorite-image/user/${userId}`,
      roles: ["MEMBER", "ADMIN"],
      description: "Get all favorite images for a user",
      command: (userId = "1") => `/api/user-favorite-image/user/${userId}`,
    },
    userImageToggle: {
      method: "GET|POST|DELETE",
      path: (userId, imageId) =>
        `/api/user-favorite-image/user/${userId}/image/${imageId}`,
      roles: ["MEMBER", "ADMIN"],
      description: "Toggle image favorite for user",
      command: (userId = "1", imageId = "2") =>
        `/api/user-favorite-image/user/${userId}/image/${imageId}`,
    },
    toggle: {
      method: "POST",
      path: "/api/user-favorite-image/toggle",
      roles: ["MEMBER", "ADMIN"],
      description: "Toggle user favorite image status",
      command: () => `/api/user-favorite-image/toggle`,
    },
  },
  userPreference: {
    list: {
      method: "GET",
      path: "/api/user-preference",
      roles: ["USER", "MEMBER", "ADMIN"],
      description: "Get list of user preferences",
      command: () => `/api/user-preference`,
    },
    user: {
      method: "GET",
      path: (userId) => `/api/user-preference/user/${userId}`,
      roles: ["USER", "MEMBER", "ADMIN"],
      description: "Get user preferences for a specific user",
      command: (userId = "123") => `/api/user-preference/user/${userId}`,
      location: {
        method: "GET",
        path: (userId) => `/api/user-preference/user/${userId}/location`,
        roles: ["USER", "MEMBER", "ADMIN"],
        description: "Get user location preferences",
        command: (userId = "123") =>
          `/api/user-preference/user/${userId}/location`,
      },
      email: {
        method: "GET",
        path: (userId) => `/api/user-preference/user/${userId}/email`,
        roles: ["USER", "MEMBER", "ADMIN"],
        description: "Get user email preferences",
        command: (userId = "123") =>
          `/api/user-preference/user/${userId}/email`,
      },
      notifications: {
        method: "GET",
        path: (userId) => `/api/user-preference/user/${userId}/notifications`,
        roles: ["USER", "MEMBER", "ADMIN"],
        description: "Get user notification preferences",
        command: (userId = "123") =>
          `/api/user-preference/user/${userId}/notifications`,
      },
      privacy: {
        method: "GET",
        path: (userId) => `/api/user-preference/user/${userId}/privacy`,
        roles: ["USER", "MEMBER", "ADMIN"],
        description: "Get user privacy preferences",
        command: (userId = "123") =>
          `/api/user-preference/user/${userId}/privacy`,
      },
    },
    details: {
      method: "GET",
      path: (id) => `/api/user-preference/${id}`,
      roles: ["USER", "MEMBER", "ADMIN"],
      description: "Get user preference by ID",
      command: (id = "123") => `/api/user-preference/${id}`,
    },
    create: {
      method: "POST",
      path: "/api/user-preference",
      roles: ["USER", "MEMBER", "ADMIN"],
      description: "Create a new user preference",
      command: () => `/api/user-preference`,
    },
    update: {
      method: "PUT",
      path: (id) => `/api/user-preference/${id}`,
      roles: ["USER", "MEMBER", "ADMIN"],
      description: "Update user preference by ID",
      command: (id = "123") => `/api/user-preference/${id}`,
    },
    delete: {
      method: "DELETE",
      path: (id) => `/api/user-preference/${id}`,
      roles: ["ADMIN"],
      description: "Delete user preference by ID",
      command: (id = "123") => `/api/user-preference/${id}`,
    },
  },
  userSession: {
    list: {
      method: "GET",
      path: "/api/user-session",
      roles: ["ADMIN"], // Admin-only for security (all sessions)
      description: "Get paginated list of all user sessions",
      command: () => `/api/user-session`,
    },
    details: {
      method: "GET",
      path: (id) => `/api/user-session/${id}`,
      roles: ["USER", "MEMBER", "ADMIN"], // Users can view their own, admins all
      description: "Get user session by ID",
      command: (id = "1") => `/api/user-session/${id}`,
    },
    create: {
      method: "POST",
      path: "/api/user-session",
      roles: ["USER", "MEMBER", "ADMIN"], // Users can create their own sessions
      description: "Create a new user session",
      command: () => `/api/user-session/create`,
    },
    update: {
      method: "PUT",
      path: (id) => `/api/user-session/${id}`,
      roles: ["USER", "MEMBER", "ADMIN"], // Users can update their own, admins all
      description: "Update user session by ID",
      command: (id = "1") => `/api/user-session/${id}/update`,
    },

    delete: {
      method: "DELETE",
      path: (id) => `/api/user-session/${id}`,
      roles: ["ADMIN"], // Users can delete their own, admins all
      description: "Delete user session by ID",
      command: (id = "1") => `/api/user-session/${id}/delete`,
    },
  },
  userScore: {
    list: {
      method: "GET",
      path: "/api/user/score",
      roles: ["public"],
      description: "Get paginated list of user scores (leaderboard)",
      command: () => "/api/user/score",
    },
    details: {
      method: "GET",
      path: (userId) => `/api/user/${userId}/score`,
      roles: ["public"],
      description: "Get user score by user ID",
      command: (userId = "1") => `/api/user/${userId}/score`,
    },
    leaderboard: {
      method: "GET",
      path: "/api/user/score/leaderboard",
      roles: ["public"],
      description: "Get top users leaderboard",
      command: () => "/api/user/score/leaderboard",
    },
    history: {
      method: "GET",
      path: "/api/user/score/history",
      roles: ["USER", "ADMIN"],
      description: "Get user scoring history with pagination",
      command: () => "/api/user/score/history",
    },
    adjust: {
      method: "POST",
      path: "/api/user/score/adjust",
      roles: ["ADMIN"],
      description: "Manually adjust user score (admin only)",
      command: () => "/api/user/score/adjust",
    },
    bonus: {
      method: "POST",
      path: "/api/user/score/bonus",
      roles: ["ADMIN"],
      description: "Award bonus points for campaigns or events (admin only)",
      command: () => "/api/user/score/bonus",
    },
    rebuild: {
      method: "POST",
      path: (userId) => `/api/user/${userId}/score/rebuild`,
      roles: ["ADMIN"],
      description: "Rebuild user score from events",
      command: (userId = "1") => `/api/user/${userId}/score/rebuild`,
    },
  },
  artPieceQueue: {
    list: {
      method: "GET",
      path: "/api/art-piece-queue",
      roles: ["ADMIN"],
      description: "Get list of art piece queue entries with optional filters",
      command: () => "/api/art-piece-queue",
    },
    details: {
      method: "GET",
      path: (id) => `/api/art-piece-queue/${id}`,
      roles: ["ADMIN"],
      description: "Get art piece queue entry by ID",
      command: (id = "1") => `/api/art-piece-queue/${id}`,
    },
    create: {
      method: "POST",
      path: "/api/art-piece-queue/create",
      roles: ["ADMIN"],
      description: "Create a new art piece queue entry",
      command: () => "/api/art-piece-queue/create",
    },
    update: {
      method: "PUT",
      path: (id) => `/api/art-piece-queue/${id}/update`,
      roles: ["ADMIN"],
      description: "Update art piece queue entry by ID",
      command: (id = "1") => `/api/art-piece-queue/${id}/update`,
    },
    delete: {
      method: "DELETE",
      path: (id) => `/api/art-piece-queue/${id}/delete`,
      roles: ["ADMIN"],
      description: "Delete art piece queue entry by ID",
      command: (id = "1") => `/api/art-piece-queue/${id}/delete`,
    },
    approve: {
      method: "POST",
      path: (id) => `/api/art-piece-queue/${id}/approve`,
      roles: ["ADMIN"],
      description: "Approve art piece queue entry and create art piece",
      command: (id = "1") => `/api/art-piece-queue/${id}/approve`,
    },
    reject: {
      method: "POST",
      path: (id) => `/api/art-piece-queue/${id}/reject`,
      roles: ["ADMIN"],
      description: "Reject art piece queue entry",
      command: (id = "1") => `/api/art-piece-queue/${id}/reject`,
    },
    flag: {
      method: "POST",
      path: (id) => `/api/art-piece-queue/${id}/flag`,
      roles: ["ADMIN"],
      description: "Flag art piece queue entry for review",
      command: (id = "1") => `/api/art-piece-queue/${id}/flag`,
    },
    updateStatus: {
      method: "PATCH",
      path: (id) => `/api/art-piece-queue/${id}/status`,
      roles: ["ADMIN"],
      description: "Update verification status of art piece queue entry",
      command: (id = "1") => `/api/art-piece-queue/${id}/status`,
    },
  },
  artHarvesting: {
    fetchHtml: {
      method: "POST",
      path: "/api/art-harvesting/fetch-html",
      roles: ["ADMIN"],
      description: "Fetch HTML content from URL for AI processing",
      command: () => "/api/art-harvesting/fetch-html",
    },
    extract: {
      method: "POST",
      path: "/api/art-harvesting/extract",
      roles: ["ADMIN"],
      description: "Extract art piece data from HTML using AI",
      command: () => "/api/art-harvesting/extract",
    },
    batchProcess: {
      method: "POST",
      path: "/api/art-harvesting/batch-process",
      roles: ["ADMIN"],
      description: "Process multiple art pieces in batch",
      command: () => "/api/art-harvesting/batch-process",
    },
    publish: {
      method: "POST",
      path: "/api/art-harvesting/publish",
      roles: ["ADMIN"],
      description: "Publish approved art pieces to public listings",
      command: () => "/api/art-harvesting/publish",
    },
    attachImages: {
      method: "POST",
      path: "/api/art-harvesting/attach-images",
      roles: ["ADMIN"],
      description: "Attach images from URLs to published art pieces",
      command: () => "/api/art-harvesting/attach-images",
    },
  },
  harvestBatch: {
    list: {
      method: "GET",
      path: "/api/harvest-batch",
      roles: ["ADMIN"],
      description: "Get list of harvest batches with optional filters",
      command: () => "/api/harvest-batch",
    },
    details: {
      method: "GET",
      path: (id) => `/api/harvest-batch/${id}`,
      roles: ["ADMIN"],
      description: "Get harvest batch by ID",
      command: (id = "1") => `/api/harvest-batch/${id}`,
    },
    create: {
      method: "POST",
      path: "/api/harvest-batch/create",
      roles: ["ADMIN"],
      description: "Create a new harvest batch",
      command: () => "/api/harvest-batch/create",
    },
    update: {
      method: "PUT",
      path: (id) => `/api/harvest-batch/${id}/update`,
      roles: ["ADMIN"],
      description: "Update harvest batch by ID",
      command: (id = "1") => `/api/harvest-batch/${id}/update`,
    },
    delete: {
      method: "DELETE",
      path: (id) => `/api/harvest-batch/${id}`,
      roles: ["ADMIN"],
      description: "Delete harvest batch by ID",
      command: (id = "1") => `/api/harvest-batch/${id}/delete`,
    },
    start: {
      method: "POST",
      path: (id) => `/api/harvest-batch/${id}/start`,
      roles: ["ADMIN"],
      description: "Start processing a harvest batch",
      command: (id = "1") => `/api/harvest-batch/${id}/start`,
    },
    stop: {
      method: "POST",
      path: (id) => `/api/harvest-batch/${id}/stop`,
      roles: ["ADMIN"],
      description: "Stop processing a harvest batch",
      command: (id = "1") => `/api/harvest-batch/${id}/stop`,
    },
    retry: {
      method: "POST",
      path: (id) => `/api/harvest-batch/${id}/retry`,
      roles: ["ADMIN"],
      description: "Retry failed items in a harvest batch",
      command: (id = "1") => `/api/harvest-batch/${id}/retry`,
    },
    stats: {
      method: "GET",
      path: (id) => `/api/harvest-batch/${id}/stats`,
      roles: ["ADMIN"],
      description: "Get statistics for a harvest batch",
      command: (id = "1") => `/api/harvest-batch/${id}/stats`,
    },
  },
  verificationLog: {
    list: {
      method: "GET",
      path: "/api/verification-log",
      roles: ["ADMIN"],
      description: "Get list of verification log entries with optional filters",
      command: () => "/api/verification-log",
    },
    details: {
      method: "GET",
      path: (id) => `/api/verification-log/${id}`,
      roles: ["ADMIN"],
      description: "Get verification log entry by ID",
      command: (id = "1") => `/api/verification-log/${id}`,
    },
    create: {
      method: "POST",
      path: "/api/verification-log/create",
      roles: ["ADMIN"],
      description: "Create a new verification log entry",
      command: () => "/api/verification-log/create",
    },
    update: {
      method: "PUT",
      path: (id) => `/api/verification-log/${id}/update`,
      roles: ["ADMIN"],
      description: "Update verification log entry by ID",
      command: (id = "1") => `/api/verification-log/${id}/update`,
    },
    delete: {
      method: "DELETE",
      path: (id) => `/api/verification-log/${id}`,
      roles: ["ADMIN"],
      description: "Delete verification log entry by ID",
      command: (id = "1") => `/api/verification-log/${id}/delete`,
    },
    byQueueId: {
      method: "GET",
      path: (queueId) => `/api/verification-log/queue/${queueId}`,
      roles: ["ADMIN"],
      description: "Get verification log entries for a specific queue item",
      command: (queueId = "1") => `/api/verification-log/queue/${queueId}`,
    },
  },
};

/**
 * @constant {Object} ENDPOINTS
 * @description Simplified endpoint paths for direct access in request functions.
 * @memberof CityArtWalks.Endpoints
 */
export const ENDPOINTS = {
  // Add other endpoints as needed
  NOTIFICATION_DELIVERY: {
    BASE: "/api/notification-delivery",
    STATS: "/api/notification-delivery/stats",
    RETRY: (deliveryId) => `/api/notification-delivery/${deliveryId}/retry`,
  },
};
